#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: Scala
  mode: cluster
  image: {{ .Values.image }}
  imagePullPolicy: Always
  mainClass: {{ .Values.mainClass }}
  mainApplicationFile: {{ .Values.mainApplicationFile }}
  sparkVersion: {{ .Values.sparkVersion }}
  restartPolicy:
    type: Never
  sparkConf:
    spark.app.name: {{ .Chart.Name }}
  arguments:
    {{- toYaml .Values.arguments | nindent 4 }}
  driver:
    cores: {{ .Values.driver.cores }}
    coreLimit: {{ .Values.driver.coreLimit }}
    memory:  {{ .Values.driver.memory }}
    labels:
      version: {{ .Values.sparkVersion }}
    serviceAccount: {{ .Values.serviceAccount }}
  executor:
    cores: {{ .Values.executor.cores }}
    instances: {{ .Values.executor.instances }}
    memory: {{ .Values.executor.memory }}
    labels:
      version: {{ .Values.sparkVersion }}

