################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-job-cluster
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: job-cluster
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-manager
        image: {{ .Values.image }}
        args: ["job-cluster", "--job-classname", {{ .Values.className }},
               {{- printf "-D jobmanager.rpc.address=%s-job-cluster" .Chart.Name -}},
               "-D jobmanager.rpc.port=6123",
               "-D parallelism.default=1",
               "-D blob.server.port=6124",
               "-D queryable-state.server.ports=6125",
               "--streaming=true",
               "--runner=FlinkRunner",
               "--parallelism=1",
               {{- join "," .Values.arguments -}}]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
        env:
          - name: FLINK_CONF_DIR
            value: /etc/flink
        volumeMounts:
        - name: {{ .Chart.Name }}-flink-config
          mountPath: /etc/flink
      volumes:
        - name: {{ .Chart.Name }}-flink-config
          configMap:
            name: {{ .Chart.Name }}-flink-config
