image: "bigdatadays2019/<your-last-name>-spark-s3-exporter:latest"

sparkVersion: "2.4.4"

mainClass: "bigdatadays.beam.BeamJob"

mainApplicationFile: "local:///usr/lib/spark-data/spark-jars/beam-job-1.0-SNAPSHOT.jar"

serviceAccount: <spark-operator-service-account>

arguments:
  - --runner=SparkRunner
  - --inputPath=s3://bigdatadays/<your-last-name>
  - --avroSchemaPath=avro/deposit_data.avsc
  - --host=clickhouse-0.clickhouse.default.svc.cluster.local
  - --user=default
  - --database=default
  - --table=<your-last-name>_deposit_data

driver:
  cores: 1
  coreLimit: "1200m"
  memory: "512m"

executor:
  cores: 1
  instances: 1
  memory: "512m"
